// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBN4WBf0HiJA5U-0fd_it77FP_KYQKatlc',
    appId: '1:75413264619:web:0f58d5f3e57301305446ae',
    messagingSenderId: '75413264619',
    projectId: 'eat-easy-binban',
    authDomain: 'eat-easy-binban.firebaseapp.com',
    storageBucket: 'eat-easy-binban.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2NgzyAwW-m0GWrANJmYG8wlSrChzwZeQ',
    appId: '1:75413264619:android:7664a9316b5dd7e05446ae',
    messagingSenderId: '75413264619',
    projectId: 'eat-easy-binban',
    storageBucket: 'eat-easy-binban.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUKDE7mbtlvSNGnTj5PRuo9LbFk8T2h6Y',
    appId: '1:75413264619:ios:dbc9427385a7bb795446ae',
    messagingSenderId: '75413264619',
    projectId: 'eat-easy-binban',
    storageBucket: 'eat-easy-binban.appspot.com',
    iosBundleId: 'com.example.binarybandits',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUKDE7mbtlvSNGnTj5PRuo9LbFk8T2h6Y',
    appId: '1:75413264619:ios:dbc9427385a7bb795446ae',
    messagingSenderId: '75413264619',
    projectId: 'eat-easy-binban',
    storageBucket: 'eat-easy-binban.appspot.com',
    iosBundleId: 'com.example.binarybandits',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBN4WBf0HiJA5U-0fd_it77FP_KYQKatlc',
    appId: '1:75413264619:web:8973bd2caf0b46575446ae',
    messagingSenderId: '75413264619',
    projectId: 'eat-easy-binban',
    authDomain: 'eat-easy-binban.firebaseapp.com',
    storageBucket: 'eat-easy-binban.appspot.com',
  );
}
