// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCOQ4tW1ZmrjcgHo1TaLrD8BbuNYk0gBU',
    appId: '1:497177915342:web:5eae5fcf86daba7b28059f',
    messagingSenderId: '497177915342',
    projectId: 'binary-banditss',
    authDomain: 'binary-banditss.firebaseapp.com',
    storageBucket: 'binary-banditss.appspot.com',
    measurementId: 'G-EVCLTJX78H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQxf8TYw8Kq5M7IWFPAt8ghpsEK9hWQ-4',
    appId: '1:497177915342:android:c9aa9e29e1bf359c28059f',
    messagingSenderId: '497177915342',
    projectId: 'binary-banditss',
    storageBucket: 'binary-banditss.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdUsXvtW8P_GjK7CnMDWTivxWoaCjfm9c',
    appId: '1:497177915342:ios:c5bd994f87137eb528059f',
    messagingSenderId: '497177915342',
    projectId: 'binary-banditss',
    storageBucket: 'binary-banditss.appspot.com',
    iosBundleId: 'com.example.binarybandits',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdUsXvtW8P_GjK7CnMDWTivxWoaCjfm9c',
    appId: '1:497177915342:ios:c5bd994f87137eb528059f',
    messagingSenderId: '497177915342',
    projectId: 'binary-banditss',
    storageBucket: 'binary-banditss.appspot.com',
    iosBundleId: 'com.example.binarybandits',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCOQ4tW1ZmrjcgHo1TaLrD8BbuNYk0gBU',
    appId: '1:497177915342:web:4481c39f02f0694f28059f',
    messagingSenderId: '497177915342',
    projectId: 'binary-banditss',
    authDomain: 'binary-banditss.firebaseapp.com',
    storageBucket: 'binary-banditss.appspot.com',
    measurementId: 'G-66S93HJYLQ',
  );
}
